WIP: Backport everything necessary to make DefineIndex recursively create partitioned indexes
This pulls in parts of the following commits:

This is the first commit that introduces partitioned indexes on partitions.

    commit 8b08f7d4820fd7a8ef6152a9dd8c6e3cb01e5f99
    Author: Alvaro Herrera <alvherre@alvh.no-ip.org>
    Date:   Fri Jan 19 11:49:22 2018 -0300

	Local partitioned indexes

	When CREATE INDEX is run on a partitioned table, create catalog entries
	for an index on the partitioned table (which is just a placeholder since
	the table proper has no data of its own), and recurse to create actual
	indexes on the existing partitions; create them in future partitions
	also.

	As a convenience gadget, if the new index definition matches some
	existing index in partitions, these are picked up and used instead of
	creating new ones.  Whichever way these indexes come about, they become
	attached to the index on the parent table and are dropped alongside it,
	and cannot be dropped on isolation unless they are detached first.

	To support pg_dump'ing these indexes, add commands
	    CREATE INDEX ON ONLY <table>
	(which creates the index on the parent partitioned table, without
	recursing) and
	    ALTER INDEX ATTACH PARTITION
	(which is used after the indexes have been created individually on each
	partition, to attach them to the parent index).  These reconstruct prior
	database state exactly.

	Reviewed-by: (in alphabetical order) Peter Eisentraut, Robert Haas, Amit
		Langote, Jesper Pedersen, Simon Riggs, David Rowley
	Discussion: https://postgr.es/m/20171113170646.gzweigyrgg6pwsg4@alvherre.pgsql

This commit adds to the base the previous commit gives us, and allows us to
create UNIQUE constraints on partitioned tables:

    commit eb7ed3f3063401496e4aa4bd68fa33f0be31a72f
    Author: Alvaro Herrera <alvherre@alvh.no-ip.org>
    Date:   Mon Feb 19 16:59:37 2018 -0300

	Allow UNIQUE indexes on partitioned tables

	If we restrict unique constraints on partitioned tables so that they
	must always include the partition key, then our standard approach to
	unique indexes already works --- each unique key is forced to exist
	within a single partition, so enforcing the unique restriction in each
	index individually is enough to have it enforced globally.  Therefore we
	can implement unique indexes on partitions by simply removing a few
	restrictions (and adding others.)

	Discussion: https://postgr.es/m/20171222212921.hi6hg6pem2w2t36z@alvherre.pgsql
	Discussion: https://postgr.es/m/20171229230607.3iib6b62fn3uaf47@alvherre.pgsql
	Reviewed-by: Simon Riggs, Jesper Pedersen, Peter Eisentraut, Jaime
		Casanova, Amit Langote

May need this commit- already partially backported the new function
convert_tuples_by_name_map, and it seems to be fixing some issues with ALTER
TABLE SET TYPE:

commit 3957b58b8885441c8d03bc1cfc00e47cf8cd7975
Author: Alvaro Herrera <alvherre@alvh.no-ip.org>
Date:   Mon Jan 9 19:26:58 2017 -0300

    Fix ALTER TABLE / SET TYPE for irregular inheritance

    If inherited tables don't have exactly the same schema, the USING clause
    in an ALTER TABLE / SET DATA TYPE misbehaves when applied to the
    children tables since commit 9550e8348b79.  Starting with that commit,
    the attribute numbers in the USING expression are fixed during parse
    analysis.  This can lead to bogus errors being reported during
    execution, such as:
       ERROR:  attribute 2 has wrong type
       DETAIL:  Table has type smallint, but query expects integer.

    Since it wouldn't do to revert to the original coding, we now apply a
    transformation to map the attribute numbers to the correct ones for each
    child.

    Reported by Justin Pryzby
    Analysis by Tom Lane; patch by me.
    Discussion: https://postgr.es/m/20170102225618.GA10071@telsasoft.com

May need this commit- it updates some stuff in `CompareIndexInfo` that was
brought in for the finst partitioned index commit:

    commit c266ed31a8a3beed3533e6a78faeca78234cbd43
    Author: Teodor Sigaev <teodor@sigaev.ru>
    Date:   Thu Apr 12 16:37:22 2018 +0300

	Cleanup covering infrastructure

	- Explicitly forbids opclass, collation and indoptions (like DESC/ASC etc) for
	  including columns. Throw an error if user points that.
	- Truncated storage arrays for such attributes to store only key atrributes,
	  added assertion checks.
	- Do not check opfamily and collation for including columns in
	  CompareIndexInfo()

	Discussion: https://www.postgresql.org/message-id/5ee72852-3c4e-ee35-e2ed-c1d053d45c08@sigaev.ru

Also, add tests from this commit. It has already been fully backported except these tests:

    commit 475be5e790e2db4c5c18a2d378c4498ffccb6289
    Author: Alvaro Herrera <alvherre@alvh.no-ip.org>
    Date:   Fri Jun 22 15:12:53 2018 -0400

	When index recurses to a partition, map columns numbers

	Two out of three code paths were mapping column numbers correctly if a
	partition had different column numbers than parent table, but the most
	commonly used one (recursing in CREATE INDEX to a new index on a
	partition) failed to map attribute numbers in expressions.  Oddly
	enough, attnums in WHERE clauses are already handled correctly
	everywhere.

	Reported-by: Amit Langote
	Author: Amit Langote
	Discussion: https://postgr.es/m/dce1fda4-e0f0-94c9-6abb-f5956a98c057@lab.ntt.co.jp
	Reviewed-by: Álvaro Herrera

TODO:
- Finish backporting all the functions used in DefineIndex from the above commits
- Add the INTERNAL_AUTO parts of inheritance inside the index_create function
  as they exist in the above commits